#!/bin/bash
set -e

# Creacion de la BD de datastore
if [ "$POSTGRES_USER" != "$USER_DATASTORE"]; then
    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" -d $POSTGRES_DB <<-EOSQL
        CREATE USER $USER_DATASTORE;
        CREATE DATABASE $DATABASE_DATASTORE;
        GRANT ALL PRIVILEGES ON DATABASE $DATABASE_DATASTORE TO $USER_DATASTORE;
EOSQL
else
    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" -d $POSTGRES_DB <<-EOSQL
        CREATE DATABASE $DATABASE_DATASTORE;
        GRANT ALL PRIVILEGES ON DATABASE $DATABASE_DATASTORE TO $USER_DATASTORE;
EOSQL
fi
